### ISSUE TITLE
redigo recが最初の5秒ほどしか保存されない

### ISSUE THREAD

**Issue by ken0nek** [yyoshiki41/radigo#20]
はじめまして。

こちらの手違いや勘違いでしたら申し訳ないのですが、
recオプションを実行した際に最初の5秒ほどしか保存されません。

例として、以下の番組をダウンロードしようとした際の実行結果を添付します。

[2017/11/10/金 11:30-13:00 | 高田文夫のラジオビバリー昼ズ | ニッポン放送 | radiko.jp](http://radiko.jp/#!/ts/LFR/20171110113000)
`radigo rec -id=LFR -s=20171110113000`

<img width="713" alt="screen shot 2017-11-10 at 12 38 26" src="https://user-images.githubusercontent.com/5785300/32641925-1b171e5a-c614-11e7-8398-12b0e6140985.png">

**Comment by yyoshiki41** [comment]
Hi, @ken0nek 
Thanks for your report.

ffmpeg の特定バージョン(or コンパイルオプション)が原因であることは分かっているのですが、
具体的な回避方法には着手出来ておりません。。

以下は、参考までに内部の処理の詳細です。
1. radiko から5秒毎にchunkされた番組の音声ファイルをDLする。
2. ローカルPCで、上のchunk ファイルを結合する。
　__この時に `ffmpeg concat` を使っているが特定バージョンでは失敗する。__
　__おそらく v3.3 以下だと成功する。__
3. 指定されたファイル拡張子で出力。

ファイル連結を `ffmpeg` に依存している以上、
この問題を解決するには、ffmpeg を含めて配布することかなと考えております。
（バージョン、OS を固定して、docker等でポータビリティのある形）

---

### Successful case

```bash
$ ffmpeg -version
ffmpeg version 3.3-static http://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2017 the FFmpeg developers
built with gcc 5.4.1 (Debian 5.4.1-8) 20170304
configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-5 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gray --enable-libass --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libzimg
```

### Failure case

```bash
$ ffmpeg -version
ffmpeg version 3.4 Copyright (c) 2000-2017 the FFmpeg developers
built with Apple LLVM version 9.0.0 (clang-900.0.37)
configuration: --prefix=/usr/local/Cellar/ffmpeg/3.4 --enable-shared --enable-pthreads --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-gpl --enable-libmp3lame --enable-libx264 --enable-libxvid --enable-opencl --enable-videotoolbox --disable-lzma
```

**Comment by yyoshiki41** [comment]
よろしければ、ローカルPCの ffmpeg バージョンを教えて頂けると参考にいたします。

```bash
$ ffmpeg -version
```

**Comment by ken0nek** [comment]
@yyoshiki41 ご丁寧な回答ありがとうございます。

ご指摘の通り、ffmpegのバージョンが3.4.0でした。

<img width="710" alt="screen shot 2017-11-10 at 18 06 05" src="https://user-images.githubusercontent.com/5785300/32650659-f5ad0156-c641-11e7-973b-cd2fc1d54aec.png">

**Comment by yyoshiki41** [comment]
@ken0nek 
レポートありがとうございます！

- ffmpeg v3.4.x では、稼働しないこと。
- ffmpeg v3.3.x のインストール方法。

を以下のissueにまとめました。

[CAUTION: do not use ffmpeg v3.4.x](https://github.com/yyoshiki41/radigo/issues/21)
