### ISSUE TITLE
recサブコマンドで録音時、ERROR: Failed to concat aac files: exit status 1で異常終了

### ISSUE THREAD

**Issue by kangaechu** [yyoshiki41/radigo#22]
### 問題の内容
Radiko タイムフリーでの録音時（recコマンド）に`ERROR: Failed to concat aac files: exit status 1`で異常終了する。

```
pi@pi2:~ $ bin/radigo rec -id=TBS -s=20171224010000
Now downloading.. 
- 
+------------+----------------------------------+
| STATION ID |              TITLE               |
+------------+----------------------------------+
| TBS        | JUNKサタデー　エレ片のコント太郎 |
+------------+----------------------------------+
| ERROR: Failed to concat aac files: exit status 1
```

### 実行環境
- OS: Raspbian Stretch
- ffmpeg: 3.2.9-1~deb9u1

### 原因
ダウンロード後の結合時に一度に開くファイルの数が多すぎるため

### 回避方法
ファイルディスクリプタの制限を変更することで対応。

/etc/security/limits.confに以下の行を追加
```
* soft nofile 65536
* hard nofile 65536
```

```
pi@pi2:~ $ ulimit -n
65536
pi@pi2:~ $ bin/radigo rec -id=TBS -s=20171224010000
Now downloading.. 
- 
+------------+----------------------------------+
| STATION ID |              TITLE               |
+------------+----------------------------------+
| TBS        | JUNKサタデー　エレ片のコント太郎 |
+------------+----------------------------------+
/ Completed!
/tmp/radigo/output/20171224010000-TBS.aac
```

**Comment by yyoshiki41** [comment]
@kangaechu 
Thanks for your report 👍 

ffmpeg のバージョンを上げた時に発生していて、バグかと思っていたのですが、
パフォーマンスのためか同時に扱うファイル数を増やしていた事が原因だったのですね！

ref. [CAUTION: do not use ffmpeg v3.4.x](https://github.com/yyoshiki41/radigo/issues/21)


`ulimit` での変更で対応することを、README に追記しておきます。

対応方法、教えていただきありがとうございました！
