### ISSUE TITLE
Can I use it in Overseas?

### ISSUE THREAD

**Issue by handsomekenya** [yyoshiki41/radigo#47]
Hello.
I'm listening Tokyo FM in Korea, OVERSEAS!
I'm using rajiko in Android. And It is too hard to record.
Than I found this project and I wonder can I use it. 

1. Can I use it on Raspberry pi 3(Rasbian)?
2. Can I use it normally or I'll need VPN?

Thanks.

**Comment by yyoshiki41** [comment]
Hi, @handsomekenya 

> Can I use it on Raspberry pi 3(Rasbian)?

yes, it works well.

> Can I use it normally or I'll need VPN?

sorry,
you need to set up VPN connection to record programs.
This is the radiko.jp limitations (not related this project.)
There are other ways that you setup a SaaS (e.g. AWS, GCP) account and chose the Datacenter located in Tokyo.
Then you launch a instance and run radigo.

Thanks!
