### ISSUE TITLE
Failed to ConcatAACFiles lately 

### ISSUE THREAD

**Issue by yoku0825** [yyoshiki41/radigo#52]
I failed to run radigo (at least, after 2020/05/25 this error has been occurred).
Is there any problem?

```
$ docker run --rm -v $PWD/output:/output yyoshiki41/radigo rec -id=QRR -start=20200531220000 -output=mp3
Now downloading..
|
+------------+------------------------+
| STATION ID |         TITLE          |
+------------+------------------------+
| QRR        | 水瀬いのり MELODY FLAG |
+------------+------------------------+
Failed to ConcatAACFiles
ERROR: Failed to concat aac files: exit status 1
```

**Comment by yyoshiki41** [comment]
@yoku0825 

radigo depends on ffmpeg.
This issue caused by broken compatibility with latest ffmpeg version.

Use v0.8.1 instead of latest version.
In my environment, it works fine.
```bash
$ docker pull yyoshiki41/radigo:v0.8.1
$ docker run --rm -v $PWD/output:/output yyoshiki41/radigo:v0.8.1 rec -id=QRR -start=20200531220000 -output=mp3
```

Thanks for your report!

**Comment by yoku0825** [comment]
@yyoshiki41 

Thank you for telling workaround.
v0.8.1 works fine for me, too.

**Comment by yyoshiki41** [comment]
@yoku0825 

Good 👍 
(I am always helped by your great knowledge of mysql. Thanks!)

**Comment by yyoshiki41** [comment]
bump v0.9.0

https://github.com/yyoshiki41/radigo/releases/tag/v0.9.0
