### ISSUE TITLE
Failed to get auth_token when executing rec command 

### ISSUE THREAD

**Issue by turndn** [yyoshiki41/radigo#59]
Hello,
I've faced the error `Failed to get auth_token: strconv.ParseInt: parsing "": invalid syntax` when I perform `radigo rec` command.
I've sought the problem a bit and I think the cause of this problem is authentication handling in go-radiko.

If I use radigo without login, could I skip `client.AuthorizeToken` in `rec.go` and `rec-live.go`?

**Comment by garaemon** [comment]
> I've faced the error Failed to get auth_token: strconv.ParseInt: parsing "": invalid syntax when I perform radigo rec command.

I have the same error when I run the following command:

```
$ ./radigo rec -id TBS -s 20201203190000 -o mp3
Now downloading..
| ERROR: Failed to get auth_token: strconv.ParseInt: parsing "": invalid syntax
```

**Comment by turndn** [comment]
I tried to perform the newest version of `go run ./example/auth/main.go` in `go-radiko` directory.
Then, I saw the same error message `strconv.ParseInt: parsing "": invalid syntax`
Thus, I think this issue is caused by [go-radiko](https://github.com/yyoshiki41/go-radiko) and we should move to `go-radiko` repository.

**Comment by turndn** [comment]
I saw the response of `auth1_fms` and it was 404 not found. I think the api is no longer available.

**Comment by garaemon** [comment]
In my environment, auth1_fms returns 503

```
$ wget  \
       --header="pragma: no-cache" \
       --header="X-Radiko-App: pc_1" \
       --header="X-Radiko-App-Version: 2.0.1" \
       --header="X-Radiko-User: test-stream" \
       --header="X-Radiko-Device: pc" \
       --post-data='\r\n' \
       --no-check-certificate \
       --save-headers \
       https://radiko.jp/v2/api/auth1_fms
--2020-12-04 00:33:48--  https://radiko.jp/v2/api/auth1_fms
Resolving radiko.jp (radiko.jp)... 203.211.199.120
Connecting to radiko.jp (radiko.jp)|203.211.199.120|:443... connected.
HTTP request sent, awaiting response... 503 Service Unavailable
2020-12-04 00:33:48 ERROR 503: Service Unavailable.
```

`auth1_fms` is closed and should radigo use `auth1` endpoint?

**Comment by turndn** [comment]
I've succeeded to record a program by using `auth1` and `auth2` instead of `auth*_fms`.
But, I needed to fix minor problems (e.g. replace from `POST` to `GET` etc...)

**Comment by turndn** [comment]
This pull request https://github.com/yyoshiki41/go-radiko/pull/19 seems to fix the problem.
Thank you.

**Comment by garaemon** [comment]
Thanks! I confirmed that the latest radigo can download radiko data.

**Comment by yyoshiki41** [comment]
@turndn 

Sorry for late reply.

I merged https://github.com/yyoshiki41/go-radiko/pull/19 in go-radiko.
And bump radigo@v0.10.0.
Please upgrade radigo 👍 

```bash
$ go get github.com/yyoshiki41/radigo/cmd/radigo/...@v0.10.0
$ radigo --version
v0.10.0 built with go1.15.2
```

@cabbagekobe @garaemon

> auth1_fms is closed and should radigo use auth1 endpoint?

Your resolution works well!!
Thanks for your help 😄
