### ISSUE TITLE
Failed to construct a radiko Client

### ISSUE THREAD

**Issue by sora44023** [yyoshiki41/radigo#72]
radigoをいつも使わせていただいております．本当にありがとうございます．

先週日曜までは問題なく使用できていましたが，今日使おうとしたところ
```
sora@snorlax:~$ radigo rec -a=JP13 -id=FMT -s=20221001190000
Now downloading..
| ERROR: Failed to construct a radiko Client: invalid login status code: 400
```
このようなエラーが発生しました．アカウントはプレミアムアカウントです．

自分のエリアのラジオのダウンロードは正常にできます(-aでエリアを指定しない場合ですね)．

環境は Windows10(21H2) WSL2 Ubuntu 20.04.5 LTSです．macOSでも同様の現象を確認したのでおそらく端末の問題ではないと思います．

いつ頃から変更が行われたのかわからないのですが，[radiko.jp](https://radiko.jp/member/login)のログイン画面が新しくなっていましたのでradiko側で何かしら変更が行われたことでこのような状況になっているのではないかと推測しています．よろしくお願いします．

**Comment by kangaechu** [comment]
This will fix following PR:
https://github.com/yyoshiki41/go-radiko/pull/22

**Comment by kangaechu** [comment]
I think this PR should keep opening while fixes don't merged.

**Comment by sora44023** [comment]
I'm sorry, I closed it because I'm not used to using GitHub. Open it again.

**Comment by yyoshiki41** [comment]
@sora44023 

Thanks for your report!
I published new version v0.12.0.

@kangaechu 
i'm grateful for your quick fix ⚡ ⚡ ⚡
